#!/usr/bin/env python3
import os
from urllib.parse import parse_qs
import sys

print("Content-Type: text/html\r\n")

# Detect request method
method = os.environ.get("REQUEST_METHOD", "GET")

print("<html>")
print("<head>")
print("<title>Enhanced CGI Test</title>")
print("<style>")
print("body { font-family: Arial, sans-serif; margin: 20px; }")
print("h1 { color: #333; }")
print("pre { background: #f0f0f0; padding: 10px; border-radius: 5px; }")
print("</style>")
print("</head>")
print("<body>")

print("<h1>CGI Test Script Executed</h1>")
print("<p><strong>Request Method:</strong> {}</p>".format(method))

# Explanation block
print("<h2>What Happened?</h2>")
print("<p>This page was generated by a CGI script executed by the web server.</p>")
print("<p>The server performed these steps:</p>")
print("<ol>")
print("<li>Detected the request and routed it to this script based on the URL and file extension.</li>")
print("<li>Created pipes and forked a new process to run the CGI program.</li>")
print("<li>Passed environment variables such as <code>REQUEST_METHOD</code>, <code>QUERY_STRING</code>, and <code>CONTENT_LENGTH</code>.</li>")
if method == "POST":
    print("<li>Sent the POST body to the script using the CGI stdin pipe.</li>")
print("<li>The script read the appropriate data and generated this HTML response.</li>")
print("</ol>")

print("<hr>")

# Logic per method
if method == "GET":
    query = os.environ.get("QUERY_STRING", "")
    print("<h2>GET Parameters</h2>")
    if query:
        print("<p><strong>Raw Query String:</strong></p>")
        print(f"<pre>{query}</pre>")
        params = parse_qs(query)
        print("<ul>")
        for k, v in params.items():
            values = ", ".join(v)
            print(f"<li><strong>{k}</strong> = {values}</li>")
        print("</ul>")
    else:
        print("<p>No query parameters were provided.</p>")

elif method == "POST":
    length = int(os.environ.get("CONTENT_LENGTH", "0"))
    post_data = sys.stdin.read(length) if length > 0 else ""
    print("<h2>POST Body</h2>")
    if post_data:
        print("<p><strong>Raw POST Data:</strong></p>")
        print(f"<pre>{post_data}</pre>")
        params = parse_qs(post_data)
        print("<ul>")
        for k, v in params.items():
            values = ", ".join(v)
            print(f"<li><strong>{k}</strong> = {values}</li>")
        print("</ul>")
    else:
        print("<p>No POST body was received.</p>")

else:
    print("<p>Unsupported Method</p>")

print("<hr>")
print('<p><a href="/cgi-bin">Go back</a></p>')
print('<p><a href="/">Home</a></p>')
print("</body></html>")
