server {
    listen 9999;
    server_name hola.com;
    error_page 404 =200 jfdksladf;
#	root $PWD/html/;
	index index.html index.php;
    location /usr {
        index index.html index.php;
        cgi .php /usr/bin/php-cgi;
    }
    allowed_methods GET DELETE;
}

server {
    listen 127.0.23.67;
    server_name adios.com;
    autoindex on;
    client_max_body_size 15K;
    error_page 404 =201 eeee;
	#root /home/dagimeno;
 #   cgi .pl /usr/bin/perl;
    location / {
		#root /hola;
        #index index.html index.php;
		cgi .py /usr/bin/python3;
    }
    server_name adios.com;
}

server
{
    listen 9999;
    server_name hola.com;
}