server {
    listen 9999;
    server_name hola.com;
    #error_page 404 =302 http://localhost:9999/error/404.html;
    #error_page 403 =302 http://localhost:9999/error/403.html;
    #plo0kerror_page 404 jfdsladf;
	root ./www/jfercode;
	index index.html;
    cgi .pl /usr/bin/perl;
	autoindex off;
    location /images {
        #alias /img;
        root /usr/home;
        #index index.html index.php;
        cgi .php /usr/bin/php-cgi;
    }
	location /upload {
        #alias /img;
       	autoindex on;
        cgi .php /usr/bin/php-cgi;
		allowed_methods GET POST DELETE;
    }
	location /cgi-bin {
    	#root ./www/jfercode/cgi-bin;
    	cgi .py /usr/bin/python3;
    	#cgi .sh /bin/bash;        # opcional: habilita .sh como CGI si lo deseas
    	allowed_methods GET POST;
    	autoindex on;
	}

    # Location para probar DELETE sobre un recurso que está fuera del `root` de este server
    # Petición de prueba: DELETE http://localhost:9999/delete-outside
    location /delete-outside {
        # alias a un fichero que está fuera de ./www/jfercode (server root)
        alias /home/pavicent/webserv/www/eg_delacruz/upload/borrar.txt;
        allowed_methods DELETE;
        autoindex off;
    }
}

server {
	listen 9998;
	root ./www/jfercode/;
	cgi .bla ./cgi_tester;
	client_max_body_size 100;
	location / {
		allowed_methods GET POST;
		index index.html;
		autoindex off;
	}
	location /directory/ {
		allowed_methods GET;
        root ./YoupiBanane;
        index youpi.bad_extension;
	}
	location /post_body {
        allowed_methods POST;
    }
}

server {
    listen 127.42.42.42:4242;
    server_name adios.com;
    #autoindex on;
    client_max_body_size 15k;
    error_page 404 =201 eeee;
	root ./www/eg_delacruz;
    #alias /home/pavicent;
    cgi .py /usr/bin/python3;
    location / {
		#alias /home/dagimeno;
        #root /home/dagimeno;
        index index.html index.php;
		cgi .py /usr/bin/python3;
		allowed_methods POST GET DELETE;
    	error_page 404 =201 eeee;
		#autoindex off;
    }
    #server_name adios.com;
}

server
{
	listen 127.0.23.67:8080;
    server_name holo.com;
}