server {
    listen 9999;
    server_name hola.com;
    error_page 404 =200 jfdksladf;
	root ./www/jfercode;
	index index.html;
    cgi .pl /usr/bin/perl;
	autoindex off;
    location /images {
        #alias /img;
        root /usr/home;
        #index index.html index.php;
        cgi .php /usr/bin/php-cgi;
    }
	location /upload {
        #alias /img;
       	autoindex on;
        cgi .php /usr/bin/php-cgi;
    }
}

server {
    listen 127.42.42.42:4242;
    server_name adios.com;
    #autoindex on;
    client_max_body_size 15k;
    error_page 404 =201 eeee;
	root ./www/eg_delacruz;
    #alias /home/pavicent;
    cgi .py /usr/bin/python3;
    location / {
		#alias /home/dagimeno;
        #root /home/dagimeno;
        index index.html index.php;
		cgi .py /usr/bin/python3;
		allowed_methods POST GET DELETE;
    	error_page 404 =201 eeee;
		#autoindex off;
    }
    #server_name adios.com;
}

server
{
	listen 127.0.23.67:8080;
    server_name holo.com;
}